### ISSUE TITLE
Is this project alive?  

### ISSUE THREAD

**Issue by onacrame** [square/pysurvival#5]
Anyone out there?

**Comment by mancunian1792** [comment]
I checked the slack channel of square and came to know that the guy who created this is on paternity leave. Hopefully, he comes back and works on this.

**Comment by onacrame** [comment]
Ah ok that’s good to know.  Looks like a library with fantastic potential.

**Comment by steph-likes-git** [comment]
Hi @MotoRZR and @mancunian1792,

Thanks so much for your interest in pysurvival. 
Apologies for the delay; pysurvival is very much a one-person side project, and I had a really busy schedule last quarter for my actual Data Scientist job at Square. 

To be honest, I didn't know if the project would be popular, so I put it on the back burner. But, I'm definitely going to spend more time on it, now. As a matter of fact, my main next step is making it available on Windows.

Keep sending your comments, and share it with your friends and colleagues!
